import Head from "next/head"
import Image from "next/image"
import tw from "twin.macro"
import Row from "../components/layouts/Row"

const Home = () => {
	return (
		<div>
			<Head>
				<head>
					<title>Create Next App</title>
					<meta name="description" content="Generated by create next app" />
					<link rel="icon" href="/favicon.ico" />
				</head>
			</Head>

			<main>
				<Row>
					<h1 tw="text-6xl font-bold">Hello!</h1>
				</Row>
			</main>
		</div>
	)
}

export default Home
